name: shawnrif
favicon: null
layout_spectrum: 0
typography_spectrum: 0.515922931721434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#16110d'
    - '#897751'
    - '#dbaa57'
    - '#fedb7f'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
