name: shawnrif
favicon: null
layout_spectrum: 1
typography_spectrum: 0.515922931721434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414233'
    - '#5488c9'
    - '#7f7e6b'
    - '#fdfdfd'
    - '#c0c8c2'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.8386755168903619
  rhythmicContrast: 0.5
purpose: []
